using DataAccessLayer;
using DataObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace LogicLayer
{
    public class SupplierOrderManager : ISupplierOrderManager
    {

        /// <summary>
        /// Laura Simmonds 
        /// 
        /// Invokes a method in SupplierOrderAccessor accessor to create an order
        /// </summary>
        /// <param name="productOrder"></param>
        /// <returns>The new order id that is auto generated by the database.</returns>
        public int createSupplierOrder(int supplierId, int employeeId)
        {
            int result = 0;
            try
            {
                result = SupplierOrderAccessor.CreateSupplierOrder(supplierId, employeeId);
            }
            catch (Exception)
            {
                throw;
            }
            return result;
        }
    }
}
