cd .\scriptFiles
for %%f in (.\*) do CALL :loopbody %%f
PAUSE
GOTO: EOF
: loopbody
set oldfilename=%1
set oldfilename=%oldfilename:.\=%
set newfilename=%oldfilename:_1_=_agreement%
set newfilename=%newfilename:_2_=_app_user%
set newfilename=%newfilename:_3_=_backorder_preorder%
set newfilename=%newfilename:_4_=_category%
set newfilename=%newfilename:_5_=_charity%
set newfilename=%newfilename:_6_=_charity_products%
set newfilename=%newfilename:_7_=_commercial%
set newfilename=%newfilename:_8_=_customer%
set newfilename=%newfilename:_9_=_deal%
set newfilename=%newfilename:_10_=_deal_category%
set newfilename=%newfilename:_11_=_deal_product%
set newfilename=%newfilename:_12_=_delivery%
set newfilename=%newfilename:_13_=_delivery_type%
set newfilename=%newfilename:_14_=_dispatcher_message%
set newfilename=%newfilename:_15_=_driver%
set newfilename=%newfilename:_16_=_employee%
set newfilename=%newfilename:_17_=_employee_message%
set newfilename=%newfilename:_18_=_employee_order_responsibility%
set newfilename=%newfilename:_19_=_employee_role%
set newfilename=%newfilename:_20_=_grade%
set newfilename=%newfilename:_21_=_inspection%
set newfilename=%newfilename:_22_=_location%
set newfilename=%newfilename:_23_=_maintenance_schedule%
set newfilename=%newfilename:_24_=_maintenance_schedule_line%
set newfilename=%newfilename:_25_=_message_line%
set newfilename=%newfilename:_26_=_order_status%
set newfilename=%newfilename:_27_=_order_type%
set newfilename=%newfilename:_28_=_package%
set newfilename=%newfilename:_29_=_package_line%
set newfilename=%newfilename:_30_=_pickup%
set newfilename=%newfilename:_31_=_pickup_line%
set newfilename=%newfilename:_32_=_product%
set newfilename=%newfilename:_33_=_product_category%
set newfilename=%newfilename:_34_=_product_grade_price%
set newfilename=%newfilename:_35_=_product_lot%
set newfilename=%newfilename:_36_=_product_order%
set newfilename=%newfilename:_37_=_product_review%
set newfilename=%newfilename:_38_=_repair%
set newfilename=%newfilename:_39_=_repair_line%
set newfilename=%newfilename:_40_=_role%
set newfilename=%newfilename:_41_=_route%
set newfilename=%newfilename:_42_=_shipping_address%
set newfilename=%newfilename:_43_=_status%
set newfilename=%newfilename:_44_=_supplier%
set newfilename=%newfilename:_45_=_user_address%
set newfilename=%newfilename:_46_=_user_cart_line%
set newfilename=%newfilename:_47_=_vehicle%
set newfilename=%newfilename:_48_=_vehicle_type%
set newfilename=%newfilename:_49_=_warehouse%
set newfilename=%newfilename:_50_=_wishlist_line%
ren %oldfilename% %newfilename%
GOTO :EOF
